### PR TITLE
Silently ignore errors for GET requests to fix 'regression' from 1.8 …

### PR DESCRIPTION
**Pull request by cbeer**
…behavior

### CODE REVIEW

**Comment by cbeer** [comment]
This seems like an incredibly bad idea, but it matches previous service behavior. In 2.x, we should actually throw major errors.

**Comment by atz** [comment]
Why implement a separate rescue instead of using existing `workflow_service_exceptions_to_catch`?

**Comment by cbeer** [comment]
@atz I'm not sure I understand the question?

**Comment by cbeer** [comment]
That said, clearly I don't understand what the expected behavior for this code is. I'm going to close this and yank dor-workflow-service 1.9 for now until we can resolve it.

**Comment by atz** [comment]
The `with_retries` wrapper already does error handling for types of exceptions specified here by `workflow_service_exceptions_to_catch` so I was thinking you could just add `Faraday::ResourceNotFound` to that list.  

Now that I think about it, though, that is **not** desirable, since retrying a 404 is counterproductive.

**Comment by cbeer** [comment]
Retries isn't the problem (we are retrying all the faraday client errors, including not found). The problem is the old code used to swallow client errors as well. I'm going to submit a new commit for replicating the old behavior for 1.x, and we should properly handle it in 2.x.

**Pull request closed without merging**
